### PR TITLE
[CI] Make faster?

### PR DESCRIPTION
**Pull request by jdkent**
I made CI take a long time in #262 , and now I'm going to try to fix it.

### CODE REVIEW

**Comment by effigies** [comment]
I think what we probably want to do is split the DB tests from the basic tests, so that they're only run on one job, rather than parameterized across estimators. It was mostly done that way because there was only one real test.

**Comment by effigies** [comment]
@jdkent Sorry for jumping the gun on the last one. Is this ready to go?

**Comment by jdkent** [comment]
no worries, I should mark as work in progress until I'm ready, this is good to go!

**Comment by effigies** [comment]
Awesome, thanks!

**Pull request merged**
