### PR TITLE
Add FEMA as key value to stat path_pattern

### LINKED ISSUE #219: ValueError: Unable to construct build path with source
An error is occurring without causing the tests to fail:

e.g. https://circleci.com/gh/poldracklab/fitlins/2209

```
200227-19:12:13,534 nipype.workflow WARNING:
	 Storing result file without outputs
200227-19:12:13,536 nipype.workflow WARNING:
	 [Node] Error on "fitlins_wf.ds_l2_contrast_maps" (/scratch/fitlins_wf/ds_l2_contrast_maps)
200227-19:12:13,540 nipype.workflow ERROR:
	 Node ds_l2_contrast_maps failed to run on host 06f1c2916f08.
200227-19:12:13,541 nipype.workflow ERROR:
	 Saving crash info to /scratch/crash-20200227-191213-neuro-ds_l2_contrast_maps-43483c87-3c93-49ca-be39-a969ffe28da3.txt
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 399, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 476, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py", line 515, in _list_outputs
    ents, path_patterns, validate=False))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 1476, in build_path
    "Unable to construct build path with source {}".format(source))
ValueError: Unable to construct build path with source {'contrast': 'taskVsBaseline', 'stat': 'FEMA', 'task': 'rhymejudgment', 'space': 'MNI152NLin2009cAsym', 'subject': '01'}

200227-19:12:59,167 nipype.workflow WARNING:
	 Storing result file without outputs
200227-19:12:59,170 nipype.workflow WARNING:
	 [Node] Error on "fitlins_wf.ds_l2_contrast_plots" (/scratch/fitlins_wf/ds_l2_contrast_plots)
200227-19:12:59,172 nipype.workflow ERROR:
	 Node ds_l2_contrast_plots failed to run on host 06f1c2916f08.
200227-19:12:59,172 nipype.workflow ERROR:
	 Saving crash info to /scratch/crash-20200227-191259-neuro-ds_l2_contrast_plots-419f8c91-099b-4cbf-bdc2-1df1fc17695b.txt
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 399, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 476, in aggregate_outputs
    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py", line 515, in _list_outputs
    ents, path_patterns, validate=False))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 1476, in build_path
    "Unable to construct build path with source {}".format(source))
ValueError: Unable to construct build path with source {'contrast': 'taskVsBaseline', 'stat': 'FEMA', 'task': 'rhymejudgment', 'space': 'MNI152NLin2009cAsym', 'subject': '01'}
```

### PR DESCRIPTION
**Pull request by adelavega**
Closes #219 

Running a model now to see if it fixes it

### CODE REVIEW

**Comment by effigies** [comment]
This may be relitigating the whole FEMA discussion, but isn't the result of FEMA still a t-statistic? Should we just transform it?

**Comment by adelavega** [comment]
I would vote in favor of keeping it consistent with the type of `stat` you asked for in the StatModel, which is `FEMA` in this case. It is a t stat, but not conceptually the same.

That said, I'd buy an argument that `FEMA` is the contrast `Type` not the stat "type", so you still get a t-stat for FEMA contrasts.

**Comment by effigies** [comment]
Well, let's stick with FEMA for now and keep it moving. We can debate filenames when it comes time to standardize derivatives.

**Comment by adelavega** [comment]
This PR fixes my issue, merging

**Pull request merged**
