### PR TITLE
FIX: Retrieve RepetitionTime from BOLD file metadata

### LINKED ISSUE #175: Getting RepetitionTime meta-data from variable entities is unreliable
See https://github.com/bids-standard/pybids/issues/501 for a longer discussion but here's the summary:

The entities for variables (which include meta-data) should not be relied on to get things such as `RepetitionTime`, as pybids officially limits this to core entities (and its sort of a bug that when a model included "regressors" some entities such as `RepetitionTime` leaked in).

### PR DESCRIPTION
**Pull request by adelavega**
- Fixes #175 - Uses BOLD file to get `RepetitionTime`
- Fixes problem with DataLad not pulling requisite files for new pybids version (meta-data sidecars)
- Fixes splatting of selectors in `.get` call.

### CODE REVIEW

**Comment by adelavega** [comment]
Tests are not passing, but it seems that its not related to the PR. Probably a pybids update.

**Comment by adelavega** [comment]
Really weird, at this file exists: http://datasets.datalad.org/labs/poldrack/ds003_fmriprep/dataset_description.json

**Comment by adelavega** [comment]
Looks like the issue is that from some reason `BIDSLayout` is treating `sourcedata` as a deriv dir, even though its the main `bids_dir`:

```
> /opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py(580)add_derivatives()
    578                 'PipelineDescription', {}).get('Name')
    579             if pipeline_name is None:
--> 580                 raise ValueError("Every valid BIDS-derivatives dataset must "
    581                                  "have a PipelineDescription.Name field set "
    582                                  "inside dataset_description.json.")

ipdb> description                                                                                                                
{'BIDSVersion': '1.0.0', 'License': 'This dataset is made available under the Public Domain Dedication and License \nv1.0, whose full text can be found at \nhttp://www.opendatacommons.org/licenses/pddl/1.0/. \nWe hope that all users will follow the ODC Attribution/Share-Alike \nCommunity Norms (http://www.opendatacommons.org/norms/odc-by-sa/); \nin particular, while not legally required, we hope that all users \nof the data will acknowledge the OpenfMRI project and NSF Grant \nOCI-1131441 (R. Poldrack, PI) in any publications.', 'Name': 'Rhyme judgment', 'Authors': ['Xue, G.', 'Poldrack, R.A.']}
ipdb> deriv_dirs                                                                                                                 
['/work/ds003_fmriprep/sourcedata']
```

**Comment by adelavega** [comment]
Looks like the issue is you're not getting the files pybids requires to instantiate a `BIDSLayout` with datalad. I'm surprised your previous tests didnt catch this, as I think this would have come with 0.9.0. Anyways, hopefully this fixes them!

**Comment by adelavega** [comment]
Well, that fixed that issue but now there's another (with pybids):

```
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 717, in get
    if return_type.startswith('file'):
AttributeError: 'dict' object has no attribute 'startswith'
```
This is a surprising one to me.

**Comment by adelavega** [comment]
Yay, this is working for me now. Hopefully tests pass!

**Comment by adelavega** [comment]
Good news: fitlins tests seem to be passing:

Bad news: There's a weird sqlalchemy error in Circle relating to pybids:
```
    % (state_str(state), instance_key, state_str(existing))
sqlalchemy.orm.exc.FlushError: New instance <Entity at 0x7fd91211bc18> with identity key (<class 'bids.layout.models.Entity'>, ('contrast',), None) conflicts with persistent instance <Entity at 0x7fd91211be80>
Exited with code 1
```

**Comment by effigies** [comment]
Yup, need pybids != 0.9.3, I think.

**Comment by effigies** [comment]
(That is it's definitely fixed in 0.9.4. I think the issue was introduced in 0.9.3. Check the pybids PRs regarding the contrast entity. The breaking one was by Oscar, the restoring one was by me.)

**Comment by effigies** [comment]
Looks like all of the commits here were already merged.

**Comment by adelavega** [comment]
Oh yeah, Whoops. Well tests passed, so yay.

**Pull request closed without merging**
