### PR TITLE
FIX: Don't validate generated paths

### LINKED ISSUE #179: ValueError: Built path is not a valid BIDS filename.
```
ERROR:nipype.workflow:Saving crash info to /work/crash-20190920-195640-root-_ds_model_warning1-3fee3f5a-e79a-4af5-9c4e-31d81838c1c2.txt
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 316, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 472, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 563, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 643, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 377, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 455, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/interfaces/bids.py", line 536, in _list_outputs
    base_dir, layout.build_path(ents, path_patterns))
  File "/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/bids/layout/layout.py", line 1213, in build_path
    "spec-compliant.".format(built))
ValueError: Built path sub-NDARAC904DMU/sub-NDARAC904DMU_task-movieDM_snippet.html is not a valid BIDS filename. Please make sure all provided entity values are spec-compliant.
```

fitlins seems a bit unhappy with itself. this is assuming the `TR` fix #178

### PR DESCRIPTION
**Pull request by adelavega**
Fixes #179 

Need to wait on pybids release so that Circle pulls the new version of pybids that causes this problem.
Also depends on #178 which has other fixes.

### CODE REVIEW

**Comment by effigies** [comment]
Damn. The pypi upload is still broken. Trying to upload from my laptop, but it's crawling.

**Comment by adelavega** [comment]
That sucks. Well none of this is urgent. I opened in a separate PR given that I assumed it would be blocked for a while.

**Comment by effigies** [comment]
Tethered to my phone just to get things moving. 0.9.4 is up.

**Comment by adelavega** [comment]
@effigies this is good to go

**Comment by adelavega** [comment]
Merging, as I need it the other PR.

**Pull request merged**
