### PR TITLE
DX: Try turning off _sync_kwargs on Factor

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by effigies** [comment]
From a bisection, the following test:

```Python
#!python
from pathlib import Path
import json
from fitlins.interfaces.bids import LoadBIDSModel

model = json.loads(Path('/data/out/fitlins-tests/inputs/models/model-001_smdl.json').read_text())

loader = LoadBIDSModel(
    database_path='/data/scratch/bidsdb',
    model=model,
    selectors={'desc': 'preproc', 'space': 'MNI152NLin2009cAsym', 'subject': ['01', '02', '03']},
)

res = loader.run()
assert list(res.outputs.all_specs['t-test'][0]['metadata'].columns) == ['contrast', 'subject']
```

Began to fail in bids-standard/pybids@f1f36161c76e8a48173afdc0e6cb6041785d81db, part of https://github.com/bids-standard/pybids/pull/861.

Basically what's happening is that we're getting a design matrix column in a table that we are using for metadata. I can filter it, but I don't understand it well enough, and I'd rather not hack around it until I'm sure that the data structures being produced by pybids are now correct.

cc @adelavega

**Comment by adelavega** [comment]
It looks like its possibly the `onset` column that is leaking out

**Comment by adelavega** [comment]
I wonder if we should be testing pybids on the same models as we test fitlins to catch these issues earlier

**Comment by adelavega** [comment]
I ran the tests with the `master` image using the following:

`fitlins /home/zorro/datasets/fitlins-tests/inputs/ds000003 /home/zorro/scratch/out dataset -d /home/zorro/datasets/fitlins-tests/inputs/ds000003-fmriprep -m /home/zorro/datasets/fitlins-tests/inputs/models/model-001_smdl.json -w /home/zorro/scratch/work --participant-label 01 02 03 --space MNI152NLin2009cAsym --estimator afni --smoothing 10.0:l1:iso --n-cpus 6 --drift-model cosine --database-path /home/zorro/scratch/out/bidsdb`

Using the commit you tagged (`https://github.com/bids-standard/pybids/commit/f1f36161c76e8a48173afdc0e6cb6041785d81db`) I do get an error:

```
Traceback (most recent call last):
  File "/opt/miniconda-latest/envs/neuro/bin/fitlins", line 5, in <module>
    from fitlins.cli.run import main
  File "/opt/miniconda-latest/envs/neuro/lib/python3.9/site-packages/fitlins/cli/run.py", line 31, in <module>
    from bids.modeling import auto_model, BIDSStatsModelsGraph
  File "/opt/miniconda-latest/envs/neuro/lib/python3.9/site-packages/bids/modeling/__init__.py", line 1, in <module>
    from .statsmodels import (BIDSStatsModelsGraph, BIDSStatsModelsNode,
  File "/opt/miniconda-latest/envs/neuro/lib/python3.9/site-packages/bids/modeling/statsmodels.py", line 719
    if 'contrast' in self.node.group_by and int_name not in [None, 'intercept']
                                                                               ^
SyntaxError: invalid syntax
```

However, updating to the after my second PR, the issue goes away. 

Try again using the latest `master` version of pybids, and let me know if the issue persists.

**Comment by adelavega** [comment]
This is the second PR i'm referring to;
https://github.com/bids-standard/pybids/pull/872

Fitlins throws no error with pybids pinned at that PR.

**Comment by adelavega** [comment]
Okay, I've been testing this more and it looks like inded `f1f3636` broke FitLins, but then I tested against my 2nd PR and it seems to pass again with no errors. However, a new error comes up on `0.15.2`, which I believe stems from a separate issue, although I can't pin point it yet.

What is the exact error you are getting?

**Comment by adelavega** [comment]
Wait, I think this change was still needed to cover the issue introduced by James' PR

**Comment by adelavega** [comment]
Let me check--- but I think they were independent issues

**Pull request closed without merging**
