### PR TITLE
ENH: modify path patterns to make task optional

### PR DESCRIPTION
**Pull request by adelavega**
It should not be required to specify a task in a model (i.e. run a model across all tasks)

I modified the `PATH_PATTERNS` to make task optional. 

Need to test a bit more.

### CODE REVIEW

**Comment by effigies** [comment]
Gah. Failed to read all the way to the bottom. Hope your tests went well.

**Comment by adelavega** [comment]
Oops. I guess you have no objection in principle. I'll put WIP in the title next time. Tests still running.

**Comment by adelavega** [comment]
That worked for me, now testing again a use case w/ a task.

By the way, the group level files will look something like this with no task:

`space-MNI152NLin2009cAsym_contrast-rms_stat-effect_statmap.nii.gz`

A bit ugly but I guess that's bids compliant?

**Comment by effigies** [comment]
Yup.

**Comment by adelavega** [comment]
Okay, yup. For the record this didn't cause any problems for models w/ task for me

**Comment by effigies** [comment]
Yeah, it shouldn't have, since the only issue might be change in fallback behavior, and we're not sending multiple patterns to the same nodes.

**Pull request merged**
