### PR TITLE
MNT: Upgrade pybids to 0.13

### PR DESCRIPTION
**Pull request by adelavega**
Bump pybids to 0.13

### CODE REVIEW

**Comment by adelavega** [comment]
`'Relative difference (max of 0.0007884396129931442) greater than 0.0001 `

Is this threshold too stringent?

**Comment by adelavega** [comment]
@effigies I notice you just merged a PR that was failing with:
```
Relative difference (max of 0.00012240744770652772) greater than 0.0001 f
```

Are these tests flakey?

**Comment by effigies** [comment]
Ping @Shotgunosine RE threshold.

@adelavega What PR?

**Comment by adelavega** [comment]
I'm just looking at the last commit made to the repository

**Comment by effigies** [comment]
Got it. Yeah, that's the first I saw of this as well. Was hoping it would go away. Feel free to merge this, since it's not a new break.

**Comment by adelavega** [comment]
Haha cool. I bet we can just tweak that threshold by a bit.

**Comment by Shotgunosine** [comment]
Sorry, just saw this. Tests might need to have the threshold raised a bit.

**Comment by Shotgunosine** [comment]
@effigies, @adelavega I'm a little bit concerned that it might not just be flakey tests. It's only the nistats tests that are failing and in every failure it's failing by the same value on comparison of the same file: 
sub-01_task-rhymejudgment_space-MNI152NLin2009cAsym_contrast-taskVsBaseline_stat-z_statmap.nii.gz

for the blurto tests it's a failure of `Relative difference (max of 0.00012240744770652772) greater than 0.0001`
for the smooth tests it's a failure of `Relative difference (max of 0.0007884396129931442) greater than 0.0001`

**Comment by effigies** [comment]
Opened #285 to see if it was nilearn 0.7.1 (released March 10, after the last pass on master on March 5).

**Pull request merged**
