### PR TITLE
FIX: Validate BIDS datasets except when searching for models

### LINKED ISSUE #206: Validate BIDSLayout
Currently, `BIDSLayout` is not validated, because model files are not valid BIDS (see: https://github.com/poldracklab/fitlins/pull/204). 

This can cause other unintended problems, so it would be best to add a custom config to pass initi pybids for these files that don't pass validation.

### PR DESCRIPTION
**Pull request by effigies**
Fixes #206.

### CODE REVIEW

**Comment by effigies** [comment]
I think this should be reasonably cheap, as it only comes into play if not explicitly passing a model, and skipping `sub-*` and `.git/` has a noticeable speedup on runtime.

**Comment by adelavega** [comment]
Nice.

**Comment by adelavega** [comment]
I guess one comment I have though is that it might be a reasonable CLI option whether or not to validate the `BIDSLayout`.

**Comment by effigies** [comment]
Not sure what that would buy a user.

**Pull request merged**
