### PR TITLE
DOC: Link out to BIDS Stats Models docs instead of maintaining our own

### LINKED ISSUE #377: Fitlins should point to https://bids-standard.github.io/stats-models/
FItlins bids stats-models page is out of date and should just point to https://bids-standard.github.io/stats-models/

### PR DESCRIPTION
**Pull request by Shotgunosine**
We probably don't want to duplicate the stats models documentation in the fintlins docs. Closes #377

### CODE REVIEW

**Comment by Shotgunosine** [comment]
@effigies  and @adelavega do y'all have thoughts on this, #375 and #374?

**Comment by effigies** [comment]
Do we actually cover everything in here, over there? If so, I think dropping `model.rst` altogether in favor of consistently linking to https://bids-standard.github.io/stats-models makes sense.

**Comment by adelavega** [comment]
I think we do except the outputs section, perhaps we can leave that in? Otherwise LGTM

**Comment by Shotgunosine** [comment]
@adelavega just getting back to this now. Which outputs section did you mean? Just this sentence? "The output of this level will again be a statistical map for the contrast a_vs_b, but summarized across the whole group."

@effigies, sounds good.

**Review by Shotgunosine — COMMENTED** [review]
I don't know why, but switching from changes.rst to changes.md means that all of the version numbers get included in the toctree. I haven't been able to find a way to stop this
Screen Shot 2022-07-28 at 12 35 16 PM
.

**Comment by adelavega** [comment]
I think that's all I meant but it doesn't seem very important now. I'm no help w/ the rst/md thing. 

Otherwise still LGTM

**Comment by effigies** [comment]
@Shotgunosine Pushed a fix. Thanks for catching that.

**Comment by effigies** [comment]
Failures unrelated. Diagnosing separately.

**Pull request merged**
