### PR TITLE
[MAINT] use latest coverage

### PR DESCRIPTION
**Pull request by jdkent**
Test using the latest version of coverage

### CODE REVIEW

**Comment by effigies** [comment]
It's probably the `sed` command that's the problem [here](https://app.circleci.com/pipelines/github/poldracklab/fitlins/113/workflows/f875b658-ac0f-4e37-abf8-3dfcfec3b390/jobs/2872). Could you remove that? Then I should be able to rerun with SSH and try to debug.

**Comment by jdkent** [comment]
```
No source for code: '/opt/miniconda-latest/envs/neuro/lib/python3.6/site-packages/fitlins/__about__.py'.
Aborting report output, consider using -i.
```

Now I see what the sed statements were for.

**Comment by effigies** [comment]
Yup. Worked fine when it was a text file, but sqlite is not so easily manipulated.

**Comment by effigies** [comment]
Coverage: It's impossible!™

**Comment by effigies** [comment]
Somewhere along the lines we/coverage/codecov/somebody seems to have resolved most of the issues. Finishing up in #354.

**Pull request closed without merging**
