### PR TITLE
WIP: Circle test for AFNI

### PR DESCRIPTION
**Pull request by effigies**
Extending on #171 to run tests.

Diagnosing issues led to #198 and #199. Assuming those pass without issue, I'll rebase to refocus this PR.

@leej3

### CODE REVIEW

**Comment by effigies** [comment]
@leej Have you tested this locally? At least on Circle, it seems to take a *very* long time on the post-RemlFit phase of FirstLevelModel.

**Comment by leej3** [comment]
Ah. That would be a bug. I think a change to 3dpval makes a certain version
of AFNI (round about when I submitted the pull request) a requirement. A
version check will probably have to be added to defensively fail. I think
3dPval hangs with your current version.

**Comment by leej3** [comment]
A new neurodebian release shouldn't be too long now. There is one pernicious bug that has slowed down the process: https://github.com/afni/afni/issues/131

**Comment by effigies** [comment]
Sounds good. Is it important to use 3dPval? We can also do simple math in Python.

**Comment by leej3** [comment]
It’s not no. I was just doing a pure afni implementation to have the comparison available. And nistats compute all of the stat maps at once so it seemed silly to use that...

**Comment by effigies** [comment]
@leej3 Any news regarding AFNI in Neurodebian?

**Comment by leej3** [comment]
I'm still working through it. I solved the aforementioned bug but I still have a bit more to do. I am struggling to get suma to work in my test container. The OpenGL dependency makes things tricky. I'm getting through it, it's just painfully slow. If it takes too much longer I can rethink things: I can either alter my CI tests to not use a container for the tests on CI (though I may very well run into the same issues because I will need headless execution), or skip the packaging of suma for now and just do a release without suma. 

Here's hoping I just figure it out quickly.

**Comment by effigies** [comment]
Okay. Looks like we're getting somewhere, but we're also hanging (working?) for hours. I'll try to see if I can get this going locally so I can debug.

**Comment by leej3** [comment]
I think the 'aforementioned bug' was ambiguous. It was referring to an issue with linking in suma. The bug with 3dPval mentioned in this thread is still going to cause the tests to hang. They won't work until a more recent neurodebian release is made. Still working on that. There is endless list of details to work through but its moving forward.

**Comment by effigies** [comment]
Oh, I see. I thought 3dPval was just missing...

Let me know if there's something useful I can do on the AFNI/NeuroDebian end.

**Comment by leej3** [comment]
Thanks, will do.

**Comment by Shotgunosine** [comment]
Closing since these changes were cherrypicked into #171 .

**Pull request closed without merging**
