### PR TITLE
ENH: Writeout estimator to derivative description

### LINKED ISSUE #273: Add estimator used to dataset_description
Currently it's not easy to get that information in a machine readable way. 

cc: @Shotgunosine maybe you can tackle this if you end up working on this next week

### PR DESCRIPTION
**Pull request by adelavega**
Closes #273 

Adds estimator selected to the `dataset_description.json`

### CODE REVIEW

**Comment by adelavega** [comment]
@effigies what do you think of the place I put it in the desc file? I could image it being one level up as well, but it seemed more appropriate under `PipelineDescription`.

I guess while we're at it we could add a bunch of other information as well, like most of the CLI flags honestly.  WDYT?

**Comment by adelavega** [comment]
Actually, looked through the CLI args, and not too many seem consequential enough to output, aside from `smoothing`. Added that one.

**Comment by effigies** [comment]
What if we just put in the full CLI invocation string? Alternately, maybe a "Parameters" object, rather than putting these directly in there?

**Comment by adelavega** [comment]
We could. That would certainly cover all of our bases. `Parameters` object nested at which level?

**Comment by effigies** [comment]
I was thinking parameters at the level you currently have things. Arg string would only be useful paired with the original version. We could look at fMRIPrep's config for complete parameter exposition.

**Comment by adelavega** [comment]
How about a dict version of the results of arg parse? That should include defaults and stick those under `Parameters`

**Comment by adelavega** [comment]
Here's en example of that:
```
{
    "Name": "Fitlins output",
    "BIDSVersion": "1.1.0",
    "PipelineDescription": {
        "Name": "FitLins",
        "Version": "0+unknown",
        "CodeURL": "https://github.com/poldracklab/fitlins",
        "Parameters": {
            "bids_dir": "/work/Budapest/derivatives/fmriprep",
            "output_dir": "/out/A13DD", "analysis_l
evel": "dataset", "verbose": 0, "quiet": 0, "participant_label": null, "model": "/work/Budapest/neuroscout-bundles/A13DD/model.json", "derivatives": ["/work/Budapest/neuroscout-bundles/A13DD /work/Budapest/derivatives/fmriprep"], "derivative_label": null, "space": "MNI152NLin
2009cAsym", "force_index": null, "ignore": ["/(.*desc-confounds_regressors.tsv)/"], "desc_label": "preproc", "database_path": null, "smoothing": "4:Dataset", "n_cpus": 16, "mem_gb": 0, "debug": false, "reports_only": false, "work_dir": "/work/fitlins/A13DD", "drop_missing": f
alse,
            "estimator": "afni",
            "error_ts": false
        }
    },
    "CodeURL": "https://github.com/poldracklab/fitlins",
    "HowToAcknowledge": "https://github.com/poldracklab/fitlins",
    "License": "CC0"
}
```

Probably should blacklist a few of these that refer to user dirs?
```

**Comment by Shotgunosine** [comment]
I don't know if we necessarily need to blacklist them. Are you concerned about leaking PII?

**Comment by effigies** [comment]
Filesystem paths could leak usernames, network share names, and give hints about other data that might be findable if someone hacked you. Seems fine to truncate to final path element, like `.../fmriprep` `.../A13DD`?

**Comment by adelavega** [comment]
Okay I added sanitization:
``
{"Name": "Fitlins output", "BIDSVersion": "1.1.0", "PipelineDescription": {"Name": "FitLins", "Version": "0+unknown", "CodeURL": "https://github.com/poldracklab/fitlins", "Parameters": {"bids_dir": "../fmriprep", "output_dir": "../A13DD", "analysis_level": "dataset", "verbose": 0, "quiet": 0, "participant_label": null, "model": "../model", "derivatives": ["../fmriprep"], "derivative_label": null,
"space": "MNI152NLin2009cAsym", "force_index": null, "ignore": ["/(.*desc-confounds_regressors.tsv)/"], "desc_label": "preproc", "database_path": null, "smoothing": "4:Dataset", "n_cpus": 16, "mem_gb": 0, "debug": false, "reports_only": false, "work_dir": "../A13DD", "drop_missing": false, "estimator": "afni", "error_ts": false}}, "CodeURL": "https://github.com/poldracklab/fitlins", "HowToAcknowledge": "https://github.com/poldracklab/fitlins", "License": "CC0"}
```

**Comment by adelavega** [comment]
ready to merge @effigies ?

**Comment by adelavega** [comment]
allright I'm merging, tested and looks good

**Pull request merged**
