### PR TITLE
RF: Simplify entry-points, restore preproc discovery

### LINKED ISSUE #32: RFC: Default location for preproc directory
Given the BIDS App CLI:

```
$ app <bids> <out> <level> [<option> ...]
```

We should settle on a default location to look for the preprocessed dataset. In the case of:

```
$ fitlins /data/bids/ds000XYZ /data/bids/ds000xyz/derivatives <level> [...]
```

The reasonable default is `/data/bids/ds000xyz/derivatives/fmriprep`, but this is `derivatives/fmriprep`, relative to the BIDS root, and `fmriprep` relative to the output directory. When we have:

```
$ fitlins /data/bids/ds000XYZ /data/out/ds000xyz/derivatives <level> [...]
```

The options become:

* `/data/bids/ds000xyz/derivatives/fmriprep`
* `/data/out/ds000xyz/derivatives/fmriprep`

Up until now I have assumed the latter, reasoning that derivatives will tend to be kept together, even when not falling under the BIDS root directory. However, in #28, the proposed presumption is that preprocessed derivatives are special, and will be kept in the BIDS root directory even when the Fitlins derivatives to be written will go elsewhere.

It would be nice to get some intuitions from others. (I'll go ahead and tag @tyarkoni, @satra, @mgxd, @jordandekraker.)

To preempt what seems like an inevitable suggestion, I'm hesitant to make this *too* smart, where we first check for one and then the other, as adding the higher priority one to a setup that was using the lower-priority would silently change the behavior (assuming that the preprocessed files are different). A case to consider here is if the higher-priority one was misspelled (e.g. `frmiprep`), and we will silently fall back to the lower-priority one, correctly spelled directory. But maybe that's okay?

Finally, just as a UX note, the current behavior allows relative paths as well as absolute. So the actual default is `-p fmriprep`, which is resolved relative to `out_dir`. The idea here is to allow alternatives like `-p spm` or `-p feat` without requiring users to add a full path. So making the right default will affect ease-of-use in that case.

### LINKED ISSUE #34: Abstract CLI-specific logic out
To make it easier for me (or others) to use fitlins as a "library", it would be useful to abstract out logic specific to the CLI.

However, I know its not the intention for fitlins to be generally used a library, so I propose some minimalist changes. Currently the only issue I'm having relates to the `sys.exit` and retcode. Since `fitlins` forces a `sys.exit` this will also exit Neuroscout, and prevent me from doing any other operations following execution. An easy fix would be to add a `run` function that does what `main` does now (parse args, run `create_workflow`, etc), but simply returns the retcode. `main` would then call `run` and execute `sys.exit`. I would then import `run` instead of `main. 

Alternatively, parse args logic could be moved to `create_workflow` and `sys.exit` could be called in `main`, and I would import `create_workflow`.

### PR DESCRIPTION
**Pull request by effigies**
This places `sys.exit` in the `main` entry-point, to reduce the chance of unexpected exits for any external calling code.

This also restores preproc discovery, prioritizing that found in `<bids_dir>/derivatives`.

Other minor simplifications were also applied, such as allowing `argparse` to apply `os.path.abspath` to file inputs.

Closes #32 
Closes #34

### CODE REVIEW

**Comment by effigies** [comment]
@adelavega This doesn't need thorough review; just want to make sure that it doesn't break things for you.

**Comment by adelavega** [comment]
Yep, I know. I just won't get a chance to test that until tomorrow.

**Comment by effigies** [comment]
Cool. No rush.

**Comment by effigies** [comment]
I was able to run your models all the way through. I had `fmriprep` in the output directory, but that shouldn't make a difference at this point. Merging.

**Comment by adelavega** [comment]
ok cool.

**Pull request merged**
