### PR TITLE
REL: 0.3.0

### PR DESCRIPTION
**Pull request by effigies**
Now's a good time for small annoying bug fixes. It seems unlikely I'll get anything major in before the end of day, although #131 has a chance.

@adelavega I'd prefer not to break neuroscout, so if you can check master, please do.

@mgxd @satra If you've got anything please let me know.

### CODE REVIEW

**Comment by mgxd** [comment]
@effigies is sparse acquisition supported with this?

**Comment by effigies** [comment]
@mgxd Sparse acquisition requires PyBIDS to correctly generated design matrices, and PyBIDS master doesn't support sparse acquisition yet, so no. But this version should be compatible with bids-standard/pybids#376, if you want to verify with the latest master.

**Comment by mgxd** [comment]
sounds good, thanks!

**Comment by effigies** [comment]
#131 isn't going to finish today.

**Pull request merged**
