### PR TITLE
DBG: Pin nilearn 0.7.0 to check whether 0.7.1 changed statistics

### PR DESCRIPTION
**Pull request by effigies**

### CODE REVIEW

**Comment by effigies** [comment]
@Shotgunosine Looks like https://github.com/nilearn/nilearn/pull/2567 changed the way z-scores are calculated. I'm inclined to update our baselines, since it looks like this was a well-considered change.

Waiting on tests to verify that this is in fact the cause.

**Comment by Shotgunosine** [comment]
That seems likely to me given where the difference is. Looks like it's a spatially constrained set of ~ 400 voxels in a region that has z-scores near the threshold described in the issue that PR is based on. Since I already made it, here's a picture:
Screen Shot 2021-04-20 at 10 18 33 AM

I'll start running jobs to update the test datasets.

**Comment by Shotgunosine** [comment]
Looks like blurto and smooth pass under 0.7.0, i'll update the test data on gin.

**Comment by adelavega** [comment]
We found the nilearn part of the brain!

**Comment by effigies** [comment]
> Looks like nistats blurto and smooth pass under 0.7.0, i'll update the test data on gin.

Sounds good. Will we need to update pins, or will tests just grab latest?

**Comment by effigies** [comment]
> We found the nilearn part of the brain!

I would really enjoy an atlas of regions likely to be affected by upgrading a particular piece of software.

**Comment by Shotgunosine** [comment]
@effigies I think it'll just pull the new data once it's uploaded.

**Pull request closed without merging**
